/**
 * 紫宸殿传乘风"交付六宫主理权"命令规划器（PUNISH-3A）。
 *
 * 分类规则（以月初 / 命令执行时的皇后健康状态为准）：
 *   before=empress + 皇后 healthy → 处罚性剥夺（strip_harem_authority），创建 punishmentId
 *   before=empress + 皇后 sick/critical → 行政性因病暂代（empress_illness），不处罚
 *   acting/neiwu → empress → 归还宫权，不处罚
 *   acting A → acting B / neiwu → 重新委任（imperial_reassignment），不处罚
 *   no-op（目标与当前一致）→ 拒绝，不写史、不 emit
 *
 * 该文件只负责规划（纯函数），不修改任何状态。
 * GameStore.transferHaremAdministration 负责校验 → 原子提交 → emit。
 */
import { toGameTime } from "../engine/calendar/time";
import type { ContentDB } from "../engine/content/loader";
import type { EventEffect } from "../engine/content/schemas";
import type { CourtEvent, GameState, HaremAdministrationReason, HaremAdministrationState } from "../engine/state/types";
import { eligibleHaremAdministrators } from "../engine/characters/haremAdministration";
import type { ReactionBeat } from "../engine/punishments/types";
import { resolveDisplayName } from "../engine/characters/standing";

const SOVEREIGN = "player";
const SOURCE_LOCATION = "zichendian";

// ── Public types ───────────────────────────────────────────────────────────────

export type HaremAdministrationTarget =
  | { kind: "empress" }
  | { kind: "consort"; charId: string }
  | { kind: "neiwu_proxy" };

export interface TransferHaremAdministrationCommand {
  type: "transfer_harem_administration";
  target: HaremAdministrationTarget;
  /** Optional case reference. Only meaningful for punitive transfers. */
  caseId?: string;
}

export interface HaremAdministrationTransferPlan {
  isPunitive: boolean;
  /** Set only when isPunitive=true; generated by GameStore, not the planner. */
  punishmentId?: string;
  /** Empress charId when the transfer originates from empress→other; used by GameStore for punishmentId targeting. */
  empressId: string | null;
  effects: EventEffect[];
  chronicle: Omit<CourtEvent, "id">[];
  /** Base dialogue lines for the reaction beat (target's first response). */
  lines: string[];
  reactionBeats: ReactionBeat[];
}

export type HaremAdminTransferResult =
  | { ok: true; plan: HaremAdministrationTransferPlan }
  | { ok: false; reason: string };

// ── Empress finder ─────────────────────────────────────────────────────────────

function findEmpressId(state: GameState): string | null {
  for (const [id, st] of Object.entries(state.standing)) {
    if (st.rank === "huanghou" && st.lifecycle !== "deceased") return id;
  }
  return null;
}

// ── Chronicle helpers ──────────────────────────────────────────────────────────

function adminChronicle(
  from: HaremAdministrationState,
  to: HaremAdministrationState,
  reason: HaremAdministrationReason | null,
  occurredAt: ReturnType<typeof toGameTime>,
  punishmentId?: string,
): Omit<CourtEvent, "id">[] {
  return [{
    type: "harem_administration_changed",
    occurredAt,
    participants: [],
    payload: {
      from: from.mode,
      to: to.mode,
      ...(to.mode === "acting_consort" ? { toCharId: (to as { charId: string }).charId } : {}),
      ...(from.mode === "acting_consort" ? { fromCharId: (from as { charId: string }).charId } : {}),
      ...(reason ? { reason } : {}),
      ...(punishmentId ? { punishmentId } : {}),
      sourceLocation: SOURCE_LOCATION,
    },
    publicity: { scope: "palace", persistence: "institutional" },
    publicSalience: 70,
    retention: "permanent",
    tags: ["harem_administration", "imperial_decree"],
  }];
}

// ── Main planner ───────────────────────────────────────────────────────────────

/**
 * Pure planner: validates the command, classifies intent, builds effects/chronicle/lines.
 * Does NOT generate punishmentId — GameStore injects it before committing.
 */
export function planHaremAdministrationTransfer(
  db: ContentDB,
  state: GameState,
  command: TransferHaremAdministrationCommand,
): HaremAdminTransferResult {
  const now = toGameTime(state.calendar);
  const admin = state.haremAdministration;
  const target = command.target;
  const eligible = eligibleHaremAdministrators(db, state);

  // ── No-op detection ──────────────────────────────────────────────────────────
  if (admin.mode === "empress" && target.kind === "empress") {
    return { ok: false, reason: "皇后正常掌管六宫，无需变更。" };
  }
  if (admin.mode === "acting_consort" && target.kind === "consort" && admin.charId === target.charId) {
    return { ok: false, reason: "该侍君已是当前六宫协理者，无需重新委任。" };
  }
  if (admin.mode === "neiwu_proxy" && target.kind === "neiwu_proxy") {
    return { ok: false, reason: "内务府已在代理六宫事务，无需重新委任。" };
  }

  // ── Target validation ────────────────────────────────────────────────────────
  if (target.kind === "neiwu_proxy") {
    if (eligible.length > 0) {
      return { ok: false, reason: "当前存在合格候选侍君，须指定侍君协理，不得直接转内务府。" };
    }
  }

  if (target.kind === "consort") {
    const chosen = eligible.find((c) => c.id === target.charId);
    if (!chosen) {
      const char = db.characters[target.charId] ?? state.generatedConsorts[target.charId];
      const name = char?.profile.name ?? target.charId;
      return { ok: false, reason: `${name}不符合六宫协理资格（位分不足、禁足或冷宫中）。` };
    }
  }

  // ── Classification ───────────────────────────────────────────────────────────
  const restoringToEmpress = target.kind === "empress";
  const fromEmpress = admin.mode === "empress";

  // Determine if punitive: only empress→other when empress is healthy
  let isPunitive = false;
  let empressHealthStatus: string | null = null;
  let empressId: string | null = null;

  if (fromEmpress && !restoringToEmpress) {
    empressId = findEmpressId(state);
    empressHealthStatus = empressId
      ? (state.standing[empressId]?.healthStatus ?? "healthy")
      : null;
    // Only healthy empress being stripped of authority counts as punitive
    isPunitive = empressHealthStatus === "healthy";
  }

  // ── Determine reason ─────────────────────────────────────────────────────────
  // restoringToEmpress has no new reason — the chronicle entry omits reason for mode="empress".
  let reason: HaremAdministrationReason | null = null;
  if (!restoringToEmpress) {
    if (fromEmpress) {
      reason = isPunitive ? "imperial_deprivation" : "empress_illness";
    } else {
      // acting/neiwu → different target
      reason = "imperial_reassignment";
    }
  }

  // ── No-eligible guard for neiwu when there are candidates ──────────────────
  // (already validated above)

  // ── Build new haremAdministration state ─────────────────────────────────────
  let newAdminState: HaremAdministrationState;
  if (restoringToEmpress) {
    newAdminState = { mode: "empress" };
  } else if (target.kind === "consort") {
    newAdminState = { mode: "acting_consort", charId: target.charId, appointedAt: now, reason: reason! };
  } else {
    newAdminState = { mode: "neiwu_proxy", appointedAt: now, reason: reason! };
  }

  // ── Effects ──────────────────────────────────────────────────────────────────
  const effects: EventEffect[] = [
    { type: "set_harem_administration", state: newAdminState },
  ];

  // Memory for empress (always)
  if (empressId) {
    const memorySummary = isPunitive
      ? "皇帝命他人协理六宫，臣侍深感失落。"
      : "臣侍抱恙，皇帝体恤令他人暂代宫务，以免操劳不利于病情。";
    effects.push({
      type: "memory",
      char: empressId,
      entry: {
        kind: isPunitive ? "trauma" : "episodic",
        summary: memorySummary,
        strength: isPunitive ? 70 : 40,
        retention: isPunitive ? "permanent" : "slow",
        subjectIds: [SOVEREIGN, empressId],
        perspective: "target",
        triggerTags: isPunitive ? [SOVEREIGN, "strip_harem_authority"] : [SOVEREIGN, "illness_leave"],
        unresolved: isPunitive,
        emotions: isPunitive ? { fear: 30, shame: 25, anger: 20 } : { relief: 20 },
      },
    });
  }

  // Memory for new acting consort (if applicable)
  if (target.kind === "consort") {
    effects.push({
      type: "memory",
      char: target.charId,
      entry: {
        kind: "episodic",
        summary: "皇帝下旨命臣侍协理六宫，臣侍领旨，定勤勉尽心。",
        strength: 60,
        retention: "slow",
        subjectIds: [SOVEREIGN, target.charId],
        perspective: "actor",
        triggerTags: [SOVEREIGN, "harem_administration"],
        unresolved: false,
        emotions: { fear: 15, joy: 20 },
      },
    });
  }

  // ── Chronicle ─────────────────────────────────────────────────────────────────
  const chronicle = adminChronicle(admin, newAdminState, reason, now);
  // punishmentId will be injected by GameStore if isPunitive

  // ── Base lines ───────────────────────────────────────────────────────────────
  const lines = buildBaseLines(db, state, target, isPunitive, empressId, newAdminState);

  // ── Bystander reaction beats (placeholder for consequence planner) ────────────
  // Punitive case: GameStore will call planPunishmentConsequences which builds reactionBeats.
  // Non-punitive: no punishment reactions; new acting consort gets one line.
  const reactionBeats: ReactionBeat[] = [];
  if (!isPunitive && target.kind === "consort") {
    const char = db.characters[target.charId] ?? state.generatedConsorts[target.charId];
    reactionBeats.push({
      speakerId: target.charId,
      lines: [`${char?.profile.name ?? "侍君"}领旨，定当尽心协理六宫事务。`],
    });
  }

  return {
    ok: true,
    plan: { isPunitive, empressId, effects, chronicle, lines, reactionBeats },
  };
}

// ── Line builder ───────────────────────────────────────────────────────────────

function buildBaseLines(
  db: ContentDB,
  state: GameState,
  target: HaremAdministrationTarget,
  isPunitive: boolean,
  empressId: string | null,
  newAdmin: HaremAdministrationState,
): string[] {
  if (target.kind === "empress") {
    return ["六宫主理权归还皇后，皇后领旨谢恩。"];
  }
  if (target.kind === "neiwu_proxy") {
    return isPunitive
      ? ["内务府总管奉旨暂代六宫事务，皇后领旨谢恩。"]
      : ["皇后抱恙，朕命内务府暂代宫务，以减皇后劳顿。"];
  }
  // acting_consort
  if (newAdmin.mode !== "acting_consort") return [];
  const char = db.characters[newAdmin.charId] ?? state.generatedConsorts[newAdmin.charId];
  const st = state.standing[newAdmin.charId];
  const rank = st ? db.ranks[st.rank] : undefined;
  const name = char ? resolveDisplayName(char, st!, rank) : newAdmin.charId;
  const empressName = empressId
    ? (db.characters[empressId]?.profile.name ?? "皇后")
    : "皇后";
  if (isPunitive) {
    return [`朕命${name}协理六宫，${empressName}领旨。`];
  }
  return [`${empressName}抱恙，朕命${name}暂理六宫，以减${empressName}劳顿。`];
}
